# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = %(here)s/backend/alembic

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
timezone = UTC

# max length of characters to apply to the "slug" field
truncate_slug_length = 40

# the output encoding used when revision files are written from script.py.mako
output_encoding = utf-8

# database URL is dynamically retrieved from application settings in env.py,
# but can be specified or overridden here if needed.
# sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/crypto_tracer

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
